parameters:
    ibnab_pmanager.form.subscriber.pdftemplate.class:        Ibnab\Bundle\PmanagerBundle\Form\EventListener\BuildTemplateFormSubscriber
    ibnab_pmanager.form.type.pdftemplate.class:              Ibnab\Bundle\PmanagerBundle\Form\Type\PDFTemplateType
    ibnab_pmanager.form.type.pdftemplate_select.class:       Ibnab\Bundle\PmanagerBundle\Form\Type\PDFTemplateSelectType
    ibnab_pmanager.form.type.pdftemplate_translation.class:  Ibnab\Bundle\PmanagerBundle\Form\Type\PDFTemplateTranslationType
    ibnab_pmanager.form.handler.pdftemplate.class:           Ibnab\Bundle\PmanagerBundle\Form\Handler\PDFTemplateHandler
    ibnab_pmanager.form.handler.exportpdf.class:             Ibnab\Bundle\PmanagerBundle\Form\Handler\ExportPDFHandler
    ibnab_pmanager.form.type.pdftemplate.api.class:          Ibnab\Bundle\PmanagerBundle\Form\Type\PDFTemplateApiType
    ibnab_pmanager.form.type.exportpdf.class:                Ibnab\Bundle\PmanagerBundle\Form\Type\ExportPDFType
    ibnab_pmanager.form.repository.pdftemplate.class:        Ibnab\Bundle\PmanagerBundle\Entity\Repository\PDFTemplateRepository
services:
    ibnab_pmanager.form.type.pdftemplate.api:
        class: %ibnab_pmanager.form.type.pdftemplate.api.class%
        arguments:
            - @oro_config.user
            - @oro_locale.settings
    ibnab_pmanager.form.subscriber.pdftemplate:
        class: %ibnab_pmanager.form.subscriber.pdftemplate.class%
        arguments:
            - @security.context

    ibnab_pmanager.form.pdftemplate:
        class: Symfony\Component\Form\Form
        factory_method: createNamed
        factory_service: form.factory
        arguments: ["ibnab_pmanager_pdftemplate", "ibnab_pmanager_pdftemplate", null]

    ibnab_pmanager.form.type.pdftemplate:
        class: %ibnab_pmanager.form.type.pdftemplate.class%
        arguments:
            - @oro_config.user
            - @oro_locale.settings
        tags:
            - { name: form.type, alias: ibnab_pmanager_pdftemplate }

    ibnab_pmanager.form.type.pdftemplate_translation:
        class: %ibnab_pmanager.form.type.pdftemplate_translation.class%
        arguments:
            - @oro_config.user
        tags:
            - { name: form.type, alias: ibnab_pmanager_pdftemplate_translatation }

    ibnab_pmanager.form.type.pdftemplate_select:
        class: %ibnab_pmanager.form.type.pdftemplate_select.class%
        tags:
            - { name: form.type, alias: ibnab_pmanager_pdftemplate_list }

    ibnab_pmanager.form.handler.pdftemplate:
        class: %ibnab_pmanager.form.handler.pdftemplate.class%
        scope: request
        arguments:
            - @ibnab_pmanager.form.pdftemplate  
            - @request
            - @doctrine.orm.entity_manager
            - @translator
    ibnab_pmanager.form.handler.exportpdf:
        class: %ibnab_pmanager.form.handler.exportpdf.class%
        scope: request
        arguments: 
            - @request
            - @ibnab_pmanager.form.repository.pdftemplate
    ibnab_pmanager.form.repository.pdftemplate:
        class: %ibnab_pmanager.form.repository.pdftemplate.class%
        factory_service: doctrine.orm.entity_manager
        factory_method: getRepository
        arguments:
            - Ibnab\Bundle\PmanagerBundle\Entity\PDFTemplate
    ibnab_pmanager.form.type.exportpdf:
        class: %ibnab_pmanager.form.type.exportpdf.class%
        arguments:
            - @security.context
            - @request_stack
        tags:
            - { name: form.type, alias: ibnab_pmanager_exportpdf }
